spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaMessageOrderTopic: "order-topic"
    kafkaMessageOrderStatusTopic: "order-status-topic"
    kafkaMessageGroupId: "order-status-service-group-id"
server:
  port: 8082
